// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: static_transform_config.proto

#include "static_transform_config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace cti {
namespace common {
class StaticTransformFileDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StaticTransformFile>
      _instance;
} _StaticTransformFile_default_instance_;
class StaticTransformConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StaticTransformConfig>
      _instance;
} _StaticTransformConfig_default_instance_;
}  // namespace common
}  // namespace cti
namespace protobuf_static_5ftransform_5fconfig_2eproto {
void InitDefaultsStaticTransformFileImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::cti::common::_StaticTransformFile_default_instance_;
    new (ptr) ::cti::common::StaticTransformFile();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::cti::common::StaticTransformFile::InitAsDefaultInstance();
}

void InitDefaultsStaticTransformFile() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsStaticTransformFileImpl);
}

void InitDefaultsStaticTransformConfigImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_static_5ftransform_5fconfig_2eproto::InitDefaultsStaticTransformFile();
  {
    void* ptr = &::cti::common::_StaticTransformConfig_default_instance_;
    new (ptr) ::cti::common::StaticTransformConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::cti::common::StaticTransformConfig::InitAsDefaultInstance();
}

void InitDefaultsStaticTransformConfig() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsStaticTransformConfigImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cti::common::StaticTransformFile, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cti::common::StaticTransformFile, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cti::common::StaticTransformFile, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cti::common::StaticTransformFile, file_path_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cti::common::StaticTransformFile, enable_),
  0,
  1,
  2,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cti::common::StaticTransformConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cti::common::StaticTransformConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cti::common::StaticTransformConfig, static_transform_config_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::cti::common::StaticTransformFile)},
  { 11, 17, sizeof(::cti::common::StaticTransformConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::cti::common::_StaticTransformFile_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::cti::common::_StaticTransformConfig_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "static_transform_config.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\035static_transform_config.proto\022\ncti.com"
      "mon\"F\n\023StaticTransformFile\022\014\n\004name\030\001 \001(\t"
      "\022\021\n\tfile_path\030\002 \001(\t\022\016\n\006enable\030\003 \001(\010\"Y\n\025S"
      "taticTransformConfig\022@\n\027static_transform"
      "_config\030\001 \003(\0132\037.cti.common.StaticTransfo"
      "rmFile"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 206);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "static_transform_config.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_static_5ftransform_5fconfig_2eproto
namespace cti {
namespace common {

// ===================================================================

void StaticTransformFile::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StaticTransformFile::kNameFieldNumber;
const int StaticTransformFile::kFilePathFieldNumber;
const int StaticTransformFile::kEnableFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StaticTransformFile::StaticTransformFile()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_static_5ftransform_5fconfig_2eproto::InitDefaultsStaticTransformFile();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:cti.common.StaticTransformFile)
}
StaticTransformFile::StaticTransformFile(const StaticTransformFile& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  file_path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_file_path()) {
    file_path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.file_path_);
  }
  enable_ = from.enable_;
  // @@protoc_insertion_point(copy_constructor:cti.common.StaticTransformFile)
}

void StaticTransformFile::SharedCtor() {
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  file_path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  enable_ = false;
}

StaticTransformFile::~StaticTransformFile() {
  // @@protoc_insertion_point(destructor:cti.common.StaticTransformFile)
  SharedDtor();
}

void StaticTransformFile::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  file_path_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void StaticTransformFile::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StaticTransformFile::descriptor() {
  ::protobuf_static_5ftransform_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_static_5ftransform_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StaticTransformFile& StaticTransformFile::default_instance() {
  ::protobuf_static_5ftransform_5fconfig_2eproto::InitDefaultsStaticTransformFile();
  return *internal_default_instance();
}

StaticTransformFile* StaticTransformFile::New(::google::protobuf::Arena* arena) const {
  StaticTransformFile* n = new StaticTransformFile;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StaticTransformFile::Clear() {
// @@protoc_insertion_point(message_clear_start:cti.common.StaticTransformFile)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*name_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(!file_path_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*file_path_.UnsafeRawStringPointer())->clear();
    }
  }
  enable_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool StaticTransformFile::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cti.common.StaticTransformFile)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "cti.common.StaticTransformFile.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string file_path = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_file_path()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->file_path().data(), static_cast<int>(this->file_path().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "cti.common.StaticTransformFile.file_path");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool enable = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          set_has_enable();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enable_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cti.common.StaticTransformFile)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cti.common.StaticTransformFile)
  return false;
#undef DO_
}

void StaticTransformFile::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cti.common.StaticTransformFile)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cti.common.StaticTransformFile.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional string file_path = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->file_path().data(), static_cast<int>(this->file_path().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cti.common.StaticTransformFile.file_path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->file_path(), output);
  }

  // optional bool enable = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->enable(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cti.common.StaticTransformFile)
}

::google::protobuf::uint8* StaticTransformFile::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:cti.common.StaticTransformFile)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cti.common.StaticTransformFile.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional string file_path = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->file_path().data(), static_cast<int>(this->file_path().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cti.common.StaticTransformFile.file_path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->file_path(), target);
  }

  // optional bool enable = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->enable(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cti.common.StaticTransformFile)
  return target;
}

size_t StaticTransformFile::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cti.common.StaticTransformFile)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 7u) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional string file_path = 2;
    if (has_file_path()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->file_path());
    }

    // optional bool enable = 3;
    if (has_enable()) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StaticTransformFile::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cti.common.StaticTransformFile)
  GOOGLE_DCHECK_NE(&from, this);
  const StaticTransformFile* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StaticTransformFile>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cti.common.StaticTransformFile)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cti.common.StaticTransformFile)
    MergeFrom(*source);
  }
}

void StaticTransformFile::MergeFrom(const StaticTransformFile& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cti.common.StaticTransformFile)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_file_path();
      file_path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.file_path_);
    }
    if (cached_has_bits & 0x00000004u) {
      enable_ = from.enable_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void StaticTransformFile::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cti.common.StaticTransformFile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StaticTransformFile::CopyFrom(const StaticTransformFile& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cti.common.StaticTransformFile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StaticTransformFile::IsInitialized() const {
  return true;
}

void StaticTransformFile::Swap(StaticTransformFile* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StaticTransformFile::InternalSwap(StaticTransformFile* other) {
  using std::swap;
  name_.Swap(&other->name_);
  file_path_.Swap(&other->file_path_);
  swap(enable_, other->enable_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata StaticTransformFile::GetMetadata() const {
  protobuf_static_5ftransform_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_static_5ftransform_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void StaticTransformConfig::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StaticTransformConfig::kStaticTransformConfigFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StaticTransformConfig::StaticTransformConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_static_5ftransform_5fconfig_2eproto::InitDefaultsStaticTransformConfig();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:cti.common.StaticTransformConfig)
}
StaticTransformConfig::StaticTransformConfig(const StaticTransformConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      static_transform_config_(from.static_transform_config_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:cti.common.StaticTransformConfig)
}

void StaticTransformConfig::SharedCtor() {
  _cached_size_ = 0;
}

StaticTransformConfig::~StaticTransformConfig() {
  // @@protoc_insertion_point(destructor:cti.common.StaticTransformConfig)
  SharedDtor();
}

void StaticTransformConfig::SharedDtor() {
}

void StaticTransformConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StaticTransformConfig::descriptor() {
  ::protobuf_static_5ftransform_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_static_5ftransform_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StaticTransformConfig& StaticTransformConfig::default_instance() {
  ::protobuf_static_5ftransform_5fconfig_2eproto::InitDefaultsStaticTransformConfig();
  return *internal_default_instance();
}

StaticTransformConfig* StaticTransformConfig::New(::google::protobuf::Arena* arena) const {
  StaticTransformConfig* n = new StaticTransformConfig;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StaticTransformConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:cti.common.StaticTransformConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  static_transform_config_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool StaticTransformConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cti.common.StaticTransformConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .cti.common.StaticTransformFile static_transform_config = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_static_transform_config()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cti.common.StaticTransformConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cti.common.StaticTransformConfig)
  return false;
#undef DO_
}

void StaticTransformConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cti.common.StaticTransformConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .cti.common.StaticTransformFile static_transform_config = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->static_transform_config_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->static_transform_config(static_cast<int>(i)), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cti.common.StaticTransformConfig)
}

::google::protobuf::uint8* StaticTransformConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:cti.common.StaticTransformConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .cti.common.StaticTransformFile static_transform_config = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->static_transform_config_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->static_transform_config(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cti.common.StaticTransformConfig)
  return target;
}

size_t StaticTransformConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cti.common.StaticTransformConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .cti.common.StaticTransformFile static_transform_config = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->static_transform_config_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->static_transform_config(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StaticTransformConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cti.common.StaticTransformConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const StaticTransformConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StaticTransformConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cti.common.StaticTransformConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cti.common.StaticTransformConfig)
    MergeFrom(*source);
  }
}

void StaticTransformConfig::MergeFrom(const StaticTransformConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cti.common.StaticTransformConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  static_transform_config_.MergeFrom(from.static_transform_config_);
}

void StaticTransformConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cti.common.StaticTransformConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StaticTransformConfig::CopyFrom(const StaticTransformConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cti.common.StaticTransformConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StaticTransformConfig::IsInitialized() const {
  return true;
}

void StaticTransformConfig::Swap(StaticTransformConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StaticTransformConfig::InternalSwap(StaticTransformConfig* other) {
  using std::swap;
  static_transform_config_.InternalSwap(&other->static_transform_config_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata StaticTransformConfig::GetMetadata() const {
  protobuf_static_5ftransform_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_static_5ftransform_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace cti

// @@protoc_insertion_point(global_scope)
