// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: static_transform_config.proto

#ifndef PROTOBUF_static_5ftransform_5fconfig_2eproto__INCLUDED
#define PROTOBUF_static_5ftransform_5fconfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_static_5ftransform_5fconfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsStaticTransformFileImpl();
void InitDefaultsStaticTransformFile();
void InitDefaultsStaticTransformConfigImpl();
void InitDefaultsStaticTransformConfig();
inline void InitDefaults() {
  InitDefaultsStaticTransformFile();
  InitDefaultsStaticTransformConfig();
}
}  // namespace protobuf_static_5ftransform_5fconfig_2eproto
namespace cti {
namespace common {
class StaticTransformConfig;
class StaticTransformConfigDefaultTypeInternal;
extern StaticTransformConfigDefaultTypeInternal _StaticTransformConfig_default_instance_;
class StaticTransformFile;
class StaticTransformFileDefaultTypeInternal;
extern StaticTransformFileDefaultTypeInternal _StaticTransformFile_default_instance_;
}  // namespace common
}  // namespace cti
namespace cti {
namespace common {

// ===================================================================

class StaticTransformFile : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cti.common.StaticTransformFile) */ {
 public:
  StaticTransformFile();
  virtual ~StaticTransformFile();

  StaticTransformFile(const StaticTransformFile& from);

  inline StaticTransformFile& operator=(const StaticTransformFile& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StaticTransformFile(StaticTransformFile&& from) noexcept
    : StaticTransformFile() {
    *this = ::std::move(from);
  }

  inline StaticTransformFile& operator=(StaticTransformFile&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StaticTransformFile& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StaticTransformFile* internal_default_instance() {
    return reinterpret_cast<const StaticTransformFile*>(
               &_StaticTransformFile_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(StaticTransformFile* other);
  friend void swap(StaticTransformFile& a, StaticTransformFile& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StaticTransformFile* New() const PROTOBUF_FINAL { return New(NULL); }

  StaticTransformFile* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StaticTransformFile& from);
  void MergeFrom(const StaticTransformFile& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StaticTransformFile* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string file_path = 2;
  bool has_file_path() const;
  void clear_file_path();
  static const int kFilePathFieldNumber = 2;
  const ::std::string& file_path() const;
  void set_file_path(const ::std::string& value);
  #if LANG_CXX11
  void set_file_path(::std::string&& value);
  #endif
  void set_file_path(const char* value);
  void set_file_path(const char* value, size_t size);
  ::std::string* mutable_file_path();
  ::std::string* release_file_path();
  void set_allocated_file_path(::std::string* file_path);

  // optional bool enable = 3;
  bool has_enable() const;
  void clear_enable();
  static const int kEnableFieldNumber = 3;
  bool enable() const;
  void set_enable(bool value);

  // @@protoc_insertion_point(class_scope:cti.common.StaticTransformFile)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_file_path();
  void clear_has_file_path();
  void set_has_enable();
  void clear_has_enable();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr file_path_;
  bool enable_;
  friend struct ::protobuf_static_5ftransform_5fconfig_2eproto::TableStruct;
  friend void ::protobuf_static_5ftransform_5fconfig_2eproto::InitDefaultsStaticTransformFileImpl();
};
// -------------------------------------------------------------------

class StaticTransformConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cti.common.StaticTransformConfig) */ {
 public:
  StaticTransformConfig();
  virtual ~StaticTransformConfig();

  StaticTransformConfig(const StaticTransformConfig& from);

  inline StaticTransformConfig& operator=(const StaticTransformConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StaticTransformConfig(StaticTransformConfig&& from) noexcept
    : StaticTransformConfig() {
    *this = ::std::move(from);
  }

  inline StaticTransformConfig& operator=(StaticTransformConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StaticTransformConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StaticTransformConfig* internal_default_instance() {
    return reinterpret_cast<const StaticTransformConfig*>(
               &_StaticTransformConfig_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(StaticTransformConfig* other);
  friend void swap(StaticTransformConfig& a, StaticTransformConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StaticTransformConfig* New() const PROTOBUF_FINAL { return New(NULL); }

  StaticTransformConfig* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StaticTransformConfig& from);
  void MergeFrom(const StaticTransformConfig& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StaticTransformConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cti.common.StaticTransformFile static_transform_config = 1;
  int static_transform_config_size() const;
  void clear_static_transform_config();
  static const int kStaticTransformConfigFieldNumber = 1;
  const ::cti::common::StaticTransformFile& static_transform_config(int index) const;
  ::cti::common::StaticTransformFile* mutable_static_transform_config(int index);
  ::cti::common::StaticTransformFile* add_static_transform_config();
  ::google::protobuf::RepeatedPtrField< ::cti::common::StaticTransformFile >*
      mutable_static_transform_config();
  const ::google::protobuf::RepeatedPtrField< ::cti::common::StaticTransformFile >&
      static_transform_config() const;

  // @@protoc_insertion_point(class_scope:cti.common.StaticTransformConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::cti::common::StaticTransformFile > static_transform_config_;
  friend struct ::protobuf_static_5ftransform_5fconfig_2eproto::TableStruct;
  friend void ::protobuf_static_5ftransform_5fconfig_2eproto::InitDefaultsStaticTransformConfigImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StaticTransformFile

// optional string name = 1;
inline bool StaticTransformFile::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StaticTransformFile::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StaticTransformFile::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StaticTransformFile::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& StaticTransformFile::name() const {
  // @@protoc_insertion_point(field_get:cti.common.StaticTransformFile.name)
  return name_.GetNoArena();
}
inline void StaticTransformFile::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cti.common.StaticTransformFile.name)
}
#if LANG_CXX11
inline void StaticTransformFile::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cti.common.StaticTransformFile.name)
}
#endif
inline void StaticTransformFile::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cti.common.StaticTransformFile.name)
}
inline void StaticTransformFile::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cti.common.StaticTransformFile.name)
}
inline ::std::string* StaticTransformFile::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:cti.common.StaticTransformFile.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StaticTransformFile::release_name() {
  // @@protoc_insertion_point(field_release:cti.common.StaticTransformFile.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StaticTransformFile::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:cti.common.StaticTransformFile.name)
}

// optional string file_path = 2;
inline bool StaticTransformFile::has_file_path() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StaticTransformFile::set_has_file_path() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StaticTransformFile::clear_has_file_path() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StaticTransformFile::clear_file_path() {
  file_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_file_path();
}
inline const ::std::string& StaticTransformFile::file_path() const {
  // @@protoc_insertion_point(field_get:cti.common.StaticTransformFile.file_path)
  return file_path_.GetNoArena();
}
inline void StaticTransformFile::set_file_path(const ::std::string& value) {
  set_has_file_path();
  file_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cti.common.StaticTransformFile.file_path)
}
#if LANG_CXX11
inline void StaticTransformFile::set_file_path(::std::string&& value) {
  set_has_file_path();
  file_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cti.common.StaticTransformFile.file_path)
}
#endif
inline void StaticTransformFile::set_file_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_file_path();
  file_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cti.common.StaticTransformFile.file_path)
}
inline void StaticTransformFile::set_file_path(const char* value, size_t size) {
  set_has_file_path();
  file_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cti.common.StaticTransformFile.file_path)
}
inline ::std::string* StaticTransformFile::mutable_file_path() {
  set_has_file_path();
  // @@protoc_insertion_point(field_mutable:cti.common.StaticTransformFile.file_path)
  return file_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StaticTransformFile::release_file_path() {
  // @@protoc_insertion_point(field_release:cti.common.StaticTransformFile.file_path)
  clear_has_file_path();
  return file_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StaticTransformFile::set_allocated_file_path(::std::string* file_path) {
  if (file_path != NULL) {
    set_has_file_path();
  } else {
    clear_has_file_path();
  }
  file_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), file_path);
  // @@protoc_insertion_point(field_set_allocated:cti.common.StaticTransformFile.file_path)
}

// optional bool enable = 3;
inline bool StaticTransformFile::has_enable() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void StaticTransformFile::set_has_enable() {
  _has_bits_[0] |= 0x00000004u;
}
inline void StaticTransformFile::clear_has_enable() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void StaticTransformFile::clear_enable() {
  enable_ = false;
  clear_has_enable();
}
inline bool StaticTransformFile::enable() const {
  // @@protoc_insertion_point(field_get:cti.common.StaticTransformFile.enable)
  return enable_;
}
inline void StaticTransformFile::set_enable(bool value) {
  set_has_enable();
  enable_ = value;
  // @@protoc_insertion_point(field_set:cti.common.StaticTransformFile.enable)
}

// -------------------------------------------------------------------

// StaticTransformConfig

// repeated .cti.common.StaticTransformFile static_transform_config = 1;
inline int StaticTransformConfig::static_transform_config_size() const {
  return static_transform_config_.size();
}
inline void StaticTransformConfig::clear_static_transform_config() {
  static_transform_config_.Clear();
}
inline const ::cti::common::StaticTransformFile& StaticTransformConfig::static_transform_config(int index) const {
  // @@protoc_insertion_point(field_get:cti.common.StaticTransformConfig.static_transform_config)
  return static_transform_config_.Get(index);
}
inline ::cti::common::StaticTransformFile* StaticTransformConfig::mutable_static_transform_config(int index) {
  // @@protoc_insertion_point(field_mutable:cti.common.StaticTransformConfig.static_transform_config)
  return static_transform_config_.Mutable(index);
}
inline ::cti::common::StaticTransformFile* StaticTransformConfig::add_static_transform_config() {
  // @@protoc_insertion_point(field_add:cti.common.StaticTransformConfig.static_transform_config)
  return static_transform_config_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::cti::common::StaticTransformFile >*
StaticTransformConfig::mutable_static_transform_config() {
  // @@protoc_insertion_point(field_mutable_list:cti.common.StaticTransformConfig.static_transform_config)
  return &static_transform_config_;
}
inline const ::google::protobuf::RepeatedPtrField< ::cti::common::StaticTransformFile >&
StaticTransformConfig::static_transform_config() const {
  // @@protoc_insertion_point(field_list:cti.common.StaticTransformConfig.static_transform_config)
  return static_transform_config_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace cti

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_static_5ftransform_5fconfig_2eproto__INCLUDED
