
#Header header

#底盘运控上报的数据
#接近开关量
uint8 out_sig_pad0         #OUT_SIG_PAD0 = 0,
uint8 out_sig_pad1         #OUT_SIG_PAD1 = 1,
uint8 out_sig_charge       #UT_SIG_CHARGE_1 = 2,
uint8 out_sig_charge_2     #OUT_SIG_CHARGE_2 = 3,
uint8 out_sig_touch_1      #OUT_SIG_TOUCH_1 = 4,
uint8 out_sig_lock_1       #OUT_SIG_LOCK_1 = 5,
uint8 out_sig_lunpan_1     #OUT_SIG_LUNPAN_1 = 6,
uint8 out_sig_riseup       #OUT_SIG_RISEUP = 7,
uint8 out_sig_lock         #OUT_SIG_LOCK_2 = 8,
uint8 out_sig_lunpan_2     #OUT_SIG_LUNPAN_2 = 9,
uint8 out_sig_putdown      #OUT_SIG_PUTDOWN = 10,
uint8 out_sig_touch_2      #OUT_SIG_TOUCH_2 = 11,
uint8 out_sig_proxmt_l     #OUT_SIG_PROXMT_L = 12,
uint8 out_sig_proxmt_r     #OUT_SIG_PROXMT_R = 13,
uint8 out_sig_head_ultra_1  #OUT_SIG_HEAD_ULTRA_1 = 14,
uint8 out_sig_head_ultra_2  #OUT_SIG_HEAD_ULTRA_