uint8 cali_init_success
uint8 imu_cali_success
uint8 SBUSbConnected
uint8 remote_lock
uint8 roll_side
uint8 motor_slip
uint8 touch_scram
uint8 hit_detect
uint8 locked_rotor_l
uint8 locked_rotor_r
uint8 motor_current_limit_l
uint8 motor_current_limit_r
uint8 magBox_have_mag
uint8 mag0du_have_mag
uint8 mag90du_have_mag
uint8 head_ultra_l
uint8 head_ultra_r
uint8 tf_shoulder_l
uint8 tf_shoulder_r
uint8 laser_foot_lf    # left front
uint8 laser_foot_rf    # right front
uint8 laser_foot_lb    # left back
uint8 laser_foot_rb    # right back
uint8 laser_step_lf    # left front
uint8 laser_step_rf    # right front
uint8 laser_step_lb    # left back
uint8 laser_step_rb    # right back
# uint8 __reserve:5;