string mapFileId                    #地图文件id
string mapBlockId                   #Block Id
string buildingName                 #所属大楼名称
string floorName                    #所属楼层名称
string simpleFloorName              #地图楼层名称，如 1, 2, 3_N ...
string createdBy                    #创建人

string mapName                      #地图名称

string imageFileHash                #地图哈希
string descriptionFileHash          #地图描述哈希
string virtualWallFileHash          #虚拟墙哈希

uint64 imageFileTimestamp           #地图时间戳
uint64 descriptionFileTimestamp     #地图描述时间戳
uint64 virtualWallFileTimestamp     #虚拟墙时间戳

string imageFileUri                 #地图链接
string descriptionFileUri           #描述文件链接
string virtualWallFileUri           #虚拟墙链接
