
---

author: "yuxiaolei"
date: "2020-07-02"
purpose: "configuration files for recording logs."

############################
#保存的topics
#rosbag只保存下列topics，可重复
############################ 
topics:
  - "/map"
  - "/scan"
#    - "/rear_scan"
#    - "/front_scan"
  - "/front_scan_filter"
  - "/rear_scan_filter"
  - "/orbbec_camera/left_scan"
  - "/orbbec_camera/right_scan"
  - "/odom"
  - "/joint_states"
  - "/tf"
  - "/tf_static"
  - "/cloud_scheduling_node/task/request"
  - "/cloud_scheduling_node/runningStatus/notify"
  - "/cmd_vel_mux/active"
  - "/cmd_vel_mux/input/default"
  - "/cmd_vel_mux/input/docking"
  - "/cmd_vel_mux/input/elevator"
  - "/cmd_vel_mux/input/joystick"
  - "/cmd_vel_mux/input/navi"
  - "/cmd_vel_mux/input/safety"
  - "/cmd_vel_mux/input/webapp"
  - "/cmd_vel_mux/output/cmd_vel"
  - "/cmd_vel_mux/output/control"
  - "/cmd_vel_send"
  - "/move_base_simple/goal"
  - "/move_base/raw_cmd_vel"
  - "/move_base/DWAPlannerROS/global_plan"
  - "/move_base/DWAPlannerROS/trajectory_cloud"
  - "/move_base/DWAPlannerROS/local_plan"
  - "/move_base/TebLocalPlannerROS/teb_poses"
  - "/move_base/TebLocalPlannerROS/teb_markers"
  - "/move_base/GlobalPlanner/plan"
  - "/move_base/NavfnROS/plan"
  - "/move_base/NavfnROS/global_plan"
  - "/move_base/local_costmap/costmap"
  - "/move_base/local_costmap/costmap_updates"
  - "/move_base/local_costmap/footprint"
  - "/move_base/global_costmap/costmap"
  - "/move_base/global_costmap/costmap_updates"
  - "/move_base/local_costmap/dynamic_obstacle_layer/costmap"
  - "/move_base/local_costmap/local_inflation_layer/costmap"
  - "/move_base/local_costmap/local_obstacle_layer/costmap"
  - "/move_base/local_costmap/radar_layer/costmap"
  - "/move_base/local_costmap/realsense_obstacle_layer/costmap"
  - "/move_base/local_costmap/robots_layer/costmap"
  - "/move_base/local_costmap/static_layer/costmap"
  - "/move_base/local_costmap/tof_obstacle_layer/costmap"
  - "/move_base/local_costmap/ultrasonic_obstacle_layer/costmap"
  - "/initialpose"
  - "/ultra_pcloud2"
  - "/robot_state"
  - "/imu"
  - "/active_map"
  - "/agent_robot"
  - "/elevator_sensor"
  - "/robot_docking/obstacle"
  - "/robot_base/mics_summary"
  - "/robot_base/motion"
  - "/robot_base/vehicle"
  - "/robot_base/pid"
  - "/robot_base/laser"
  - "/robot_base/sensors"
  - "/robot_base/tfmini_array"
  - "/robot_base/ultrasonic"
  - "/robot_base/ultra_array"
  - "/robot_base/debug/sendcmd"
  - "/robot_base/can_err"
  - "/robot_base/add_state"
  - "/robot_base/carry_box_info"
  - "/imu_outter"
  - "/robot_base/brief_state"
  - "/smooth_variavle"
  - "wash_base/pid"
  - "/particlecloud"
  - "/robot_base/warn_value"
  - "/qrcode_rela_pose"
  - "/distinguish_cmd"
  - "/distinguish_state"
  - "/tof_scan_left"
  - "/tof_scan_right"
  - "/realsense_scan"
  - "/static_layer_plan/global_planner/plan"
  - "/lift_state"
  - "/lift_run_cmd"
  - "/box_mount_cmd"
  - "/navigation_control_cmd"
  # - "/ti_mmwave/radar_scan_pcl"
  # - "/ti_mmwave/radar_scan"
  # - "/ti_mmwave/mmwave_filter_pcl"
  - "/move_base/local_costmap/area0"
  - "/move_base/local_costmap/area1"
  - "/move_base/local_costmap/area2"
  - "/move_base/local_costmap/area3"
  - "/move_base/local_costmap/area4"
  - "/move_base/local_costmap/area5"
  - "/move_base/local_costmap/area6"
  - "/move_base/local_costmap/area7"
  - "/securitymanager_recovery_lineback_polygon"
  - "/navi_speed_decider/roi"
  - "/navi_speed_decider/ultrasound"
  - "/navi_speed_decider/visualization_marker"
  - "/orbbec_camera/left_scan"
  - "/orbbec_camera/right_scan"
  - "/navigation_mbf_ctrl_cmd"
  - "/move_base_flex/local_costmap/costmap"
  - "/move_base_flex/local_costmap/costmap_updates"
  - "/move_base_flex/local_costmap/footprint"
  - "/move_base_flex/global_costmap/costmap"
  - "/move_base_flex/global_costmap/costmap_updates"
  - "/move_base_flex/local_costmap/area0"
  - "/move_base_flex/local_costmap/area1"
  - "/move_base_flex/local_costmap/area2"
  - "/move_base_flex/local_costmap/area3"
  - "/move_base_flex/local_costmap/area4"
  - "/move_base_flex/local_costmap/area5"
  - "/move_base_flex/local_costmap/area6"
  - "/move_base_flex/local_costmap/area7"

